apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: np87q4krw-nodejs
  janus-idp.io/tekton: np87q4krw-nodejs
  backstage.io/kubernetes-id: np87q4krw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: np87q4krw-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
