apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: np87q4krw-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: np87q4krw-nodejs 
  name: np87q4krw-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: np87q4krw-nodejs 
